import { StyleSheet } from 'react-native';

export const ScreenStyles = StyleSheet.create({
  // Стили для LoginScreen
  loginScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
    justifyContent: 'center',
    padding: 20,
  },
  loginScreenHeader: {
    alignItems: 'center',
    marginBottom: 50,
  },
  loginScreenHeaderTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 8,
  },
  loginScreenHeaderSubtitle: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
  },
  loginScreenForm: {
    backgroundColor: '#FFFFFF',
    padding: 24,
    borderRadius: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  loginScreenTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 24,
    color: '#4A306D',
  },
  loginScreenLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: '#4A306D',
  },
  loginScreenInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 16,
    backgroundColor: '#F9FAFB',
    color: '#374151',
  },
  loginScreenButton: {
    backgroundColor: '#4A306D',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  loginScreenButtonDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
    elevation: 0,
  },
  loginScreenButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  loginScreenDemoContainer: {
    backgroundColor: '#F3F4F6',
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#6B7280',
  },
  loginScreenDemoTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A306D',
    marginBottom: 4,
  },
  loginScreenDemoText: {
    fontSize: 12,
    color: '#6B7280',
    fontFamily: 'monospace',
  },

  // Стили для JournalScreen
    journalScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',

  },
  journalScreenHeader: {
    marginBottom: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  journalScreenHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  journalScreenHeaderTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  journalScreenSubheader: {
    fontSize: 18,
    color: '#6B7280',
  },
  journalScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  journalScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  journalScreenMenu: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  journalScreenMenuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  journalScreenMenuItemContent: {
    flex: 1,
  },
  journalScreenMenuItemTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4A306D',
    marginBottom: 4,
  },
  journalScreenMenuItemDescription: {
    fontSize: 14,
    color: '#6B7280',
  },
  journalScreenMenuArrow: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  // Стили для AddGroupScreen
  addGroupScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
    padding: 20,
  },
  addGroupScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
    paddingTop: 60,
  },
  addGroupScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  addGroupScreenBackButton: {
    marginRight: 15,
  },
  addGroupScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  addGroupScreenHeaderTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  addGroupScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  addGroupScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  addGroupScreenInputContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  addGroupScreenInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 18,
    backgroundColor: '#F9FAFB',
    color: '#374151',
    textAlign: 'center',
    fontWeight: '600',
  },
  addGroupScreenSaveButton: {
    backgroundColor: '#4A306D',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addGroupScreenSaveButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },

  // Стили для AddLessonScreen
  addLessonScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
  },
  addLessonScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  addLessonScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  addLessonScreenBackButton: {
    marginRight: 15,
  },
  addLessonScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  addLessonScreenHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  addLessonScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  addLessonScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  addLessonScreenScrollView: {
    flex: 1,
    padding: 20,
  },
  addLessonScreenSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  addLessonScreenSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 15,
  },
  addLessonScreenTextInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#F9FAFB',
    color: '#374151',
  },

  // Стили для выбора недели в AddLessonScreen
  addLessonScreenWeekSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  addLessonScreenWeekButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginHorizontal: 5,
    backgroundColor: '#F3F4F6',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  addLessonScreenWeekButtonActive: {
    backgroundColor: '#4A306D',
    borderColor: '#4A306D',
  },
  addLessonScreenWeekButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
  },
  addLessonScreenWeekButtonTextActive: {
    color: '#FFFFFF',
  },

  // Стили для выбора дня в AddLessonScreen
  addLessonScreenDaysSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  addLessonScreenDayButton: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    marginHorizontal: 2,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  addLessonScreenDayButtonActive: {
    backgroundColor: '#4A306D',
  },
  addLessonScreenDayButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A306D',
  },
  addLessonScreenDayButtonTextActive: {
    color: '#FFFFFF',
  },
  addLessonScreenSelectedDayText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
    textAlign: 'center',
    marginTop: 10,
  },

  // Стили для выбора времени в AddLessonScreen
  addLessonScreenTimeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  addLessonScreenTimeSlot: {
    width: '48%',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 10,
    backgroundColor: '#F3F4F6',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  addLessonScreenTimeSlotActive: {
    backgroundColor: '#4A306D',
    borderColor: '#4A306D',
  },
  addLessonScreenTimeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A306D',
  },
  addLessonScreenTimeTextActive: {
    color: '#FFFFFF',
  },

  // Стили для выбора групп в AddLessonScreen
  addLessonScreenGroupsHint: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 12,
    fontStyle: 'italic',
  },

  // Стили для выбора предмета в AddLessonScreen
  addLessonScreenSubjectHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  addLessonScreenAddSubjectButton: {
    backgroundColor: '#4A306D',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  addLessonScreenAddSubjectButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  addLessonScreenSelectedSubject: {
    backgroundColor: '#F0F7FF',
    padding: 16,
    borderRadius: 12,
    marginBottom: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#4A306D',
  },
  addLessonScreenSelectedSubjectName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
  },
  addLessonScreenSubjectsScroll: {
    marginHorizontal: -5,
  },
  addLessonScreenSubjectsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 5,
  },
  addLessonScreenSubjectCard: {
    width: 140,
    padding: 16,
    borderRadius: 12,
    marginRight: 10,
    backgroundColor: '#F8F7FF',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  addLessonScreenSubjectCardActive: {
    backgroundColor: '#4A306D',
    borderColor: '#4A306D',
  },
  addLessonScreenSubjectCardName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4A306D',
    textAlign: 'center',
  },
  addLessonScreenSubjectCardNameActive: {
    color: '#FFFFFF',
  },

  // Стили для кнопки сохранения в AddLessonScreen
  addLessonScreenSaveButton: {
    backgroundColor: '#4A306D',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addLessonScreenSaveButtonDisabled: {
    backgroundColor: '#9CA3AF',
  },
  addLessonScreenSaveButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },

  // Стили для модального окна в AddLessonScreen
  addLessonScreenModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  addLessonScreenModalContent: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  addLessonScreenModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 20,
    textAlign: 'center',
  },
  addLessonScreenModalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
    marginBottom: 8,
  },
  addLessonScreenModalInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 16,
    backgroundColor: '#F9FAFB',
    color: '#374151',
  },
  addLessonScreenModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  addLessonScreenModalButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  addLessonScreenModalCancelButton: {
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    height: 52,
    justifyContent: 'center', // Добавляем для выравнивания
    alignItems: 'center',
  },
  addLessonScreenModalAddButton: {
    backgroundColor: '#4A306D',
  },
  addLessonScreenModalCancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
  },
  addLessonScreenModalAddButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  // Стили для AddStudentScreen
  addStudentScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
  },
  addStudentScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  addStudentScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  addStudentScreenBackButton: {
    marginRight: 15,
  },
  addStudentScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  addStudentScreenHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  addStudentScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  addStudentScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  addStudentScreenScrollView: {
    flex: 1,
    padding: 20,
  },
  addStudentScreenSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  addStudentScreenSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 15,
  },
  addStudentScreenLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
    marginBottom: 8,
  },
  addStudentScreenInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#F9FAFB',
    color: '#374151',
    marginBottom: 16,
  },
  addStudentScreenStudentIdContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addStudentScreenStudentIdInput: {
    flex: 1,
    marginRight: 10,
  },
  addStudentScreenGenerateButton: {
    backgroundColor: '#4A306D',
    padding: 16,
    borderRadius: 12,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addStudentScreenGenerateButtonText: {
    color: 'white',
    fontSize: 18,
  },
  addStudentScreenGenerateButtonTextDisabled: {
    opacity: 0.5,
  },
  addStudentScreenSelectedGroupContainer: {
    marginBottom: 16,
  },
  addStudentScreenSelectedGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F0F9FF',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#4A306D',
  },
  addStudentScreenSelectedGroupText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A306D',
  },
  addStudentScreenChangeGroupButton: {
    padding: 8,
  },
  addStudentScreenChangeGroupButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  addStudentScreenGroupSelection: {
    marginBottom: 16,
  },
  addStudentScreenAvailableGroupsTitle: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  addStudentScreenGroupsContainer: {
    flexDirection: 'row',
  },
  addStudentScreenGroupChip: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  addStudentScreenGroupChipText: {
    fontSize: 14,
    color: '#4A306D',
    fontWeight: '600',
  },
  addStudentScreenNoGroupsContainer: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    marginBottom: 16,
  },
  addStudentScreenNoGroupsText: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 4,
  },
  addStudentScreenNoGroupsSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  addStudentScreenDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
  },
  addStudentScreenDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  addStudentScreenDividerText: {
    paddingHorizontal: 16,
    color: '#6B7280',
    fontSize: 14,
  },
  addStudentScreenCreateGroupButton: {
    backgroundColor: 'rgba(74, 48, 109, 0.1)',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4A306D',
    borderStyle: 'dashed',
  },
  addStudentScreenCreateGroupButtonText: {
    color: '#4A306D',
    fontSize: 16,
    fontWeight: '600',
  },
  addStudentScreenSaveButton: {
    backgroundColor: '#4A306D',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addStudentScreenSaveButtonDisabled: {
    backgroundColor: '#9CA3AF',
  },
  addStudentScreenSaveButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },

  // Стили для AttendanceScreen
  attendanceScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
  },
  attendanceScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  attendanceScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  attendanceScreenBackButton: {
    marginRight: 15,
  },
  attendanceScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  attendanceScreenHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  attendanceScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  attendanceScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  attendanceScreenScrollView: {
    flex: 1,
    padding: 20,
  },
  attendanceScreenLessonInfo: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  attendanceScreenLessonSubject: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 8,
  },
  attendanceScreenLessonDetails: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 4,
  },
  attendanceScreenLessonClassroom: {
    fontSize: 14,
    color: '#9CA3AF',
    fontStyle: 'italic',
  },
  attendanceScreenSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  attendanceScreenSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  attendanceScreenSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A306D',
  },
  attendanceScreenStudentsCount: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '600',
  },
  attendanceScreenDateInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#F9FAFB',
    color: '#374151',
    textAlign: 'center',
  },
  attendanceScreenStatsSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  attendanceScreenStatItem: {
    alignItems: 'center',
  },
  attendanceScreenStatNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 4,
  },
  attendanceScreenStatLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  attendanceScreenStudentCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8F7FF',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#4A306D',
  },
  attendanceScreenStudentInfo: {
    flex: 1,
  },
  attendanceScreenStudentName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 4,
  },
  attendanceScreenStudentGroup: {
    fontSize: 14,
    color: '#6B7280',
  },
  attendanceScreenAttendanceButtons: {
    flexDirection: 'row',
    marginRight: 10,
  },
  attendanceScreenStatusButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  attendanceScreenStatusButtonActive: {
    borderColor: '#4A306D',
  },
  attendanceScreenStatusButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#6B7280',
  },
  attendanceScreenStatusButtonTextActive: {
    color: '#FFFFFF',
  },
  attendanceScreenCurrentStatus: {
    width: 20,
    alignItems: 'center',
  },
  attendanceScreenStatusBadge: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  attendanceScreenLoadingText: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 16,
    padding: 20,
  },
  attendanceScreenEmptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  attendanceScreenEmptyStateText: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 8,
  },
  attendanceScreenEmptyStateSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  attendanceScreenSaveButton: {
    backgroundColor: '#4A306D',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  attendanceScreenSaveButtonDisabled: {
    backgroundColor: '#9CA3AF',
  },
  attendanceScreenSaveButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  // Стили для ScheduleManagementScreen
  scheduleManagementScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',

  },
  scheduleManagementScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  scheduleManagementScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  scheduleManagementScreenBackButton: {
    marginRight: 15,
  },
  scheduleManagementScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  scheduleManagementScreenHeaderTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  scheduleManagementScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  scheduleManagementScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  scheduleManagementScreenMenu: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 20,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,

  },
  scheduleManagementScreenMenuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  scheduleManagementScreenMenuItemContent: {
    flex: 1,
  },
  scheduleManagementScreenMenuItemTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4A306D',
    marginBottom: 4,
  },
  scheduleManagementScreenMenuItemDescription: {
    fontSize: 14,
    color: '#6B7280',
  },
  scheduleManagementScreenMenuArrow: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
    marginLeft: 10,
  },
  scheduleManagementScreenSubjectsSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  scheduleManagementScreenSectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 15,
  },
  scheduleManagementScreenSubjectCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8F7FF',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  scheduleManagementScreenSubjectInfo: {
    flex: 1,
  },
  scheduleManagementScreenSubjectName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 4,
  },
  scheduleManagementScreenSubjectGroups: {
    fontSize: 14,
    color: '#6B7280',
  },
  scheduleManagementScreenSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  scheduleManagementScreenRefreshButton: {
    backgroundColor: 'rgba(92, 128, 188, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  scheduleManagementScreenRefreshButtonText: {
    color: '#5C80BC',
    fontSize: 16,
    fontWeight: 'bold',
  },
  scheduleManagementScreenLoadingText: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 16,
    padding: 20,
  },
  scheduleManagementScreenLessonCount: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
  },
  scheduleManagementScreenMenuItemDisabled: {
    opacity: 0.6,
  },

  // Стили для ScheduleScreen
  scheduleScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',

  },
  scheduleScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingTop: 60,     
  },
  scheduleScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  scheduleScreenHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scheduleScreenBackButton: {
    marginRight: 15,
  },
  scheduleScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  scheduleScreenHeaderTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  scheduleScreenRefreshButton: {
    backgroundColor: 'rgba(92, 128, 188, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 10,
  },
  scheduleScreenRefreshButtonText: {
    color: '#5C80BC',
    fontSize: 16,
    fontWeight: 'bold',
  },
  scheduleScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  scheduleScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  scheduleScreenWeekSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  scheduleScreenWeekSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 10,
  },
  scheduleScreenWeekButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scheduleScreenWeekButton: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginHorizontal: 5,
    backgroundColor: '#F3F4F6',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  scheduleScreenWeekButtonActive: {
    backgroundColor: '#4A306D',
    borderColor: '#4A306D',
  },
  scheduleScreenWeekButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A306D',
  },
  scheduleScreenWeekButtonTextActive: {
    color: '#FFFFFF',
  },
  scheduleScreenDaysSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  scheduleScreenDayButton: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    marginHorizontal: 4,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  scheduleScreenDayButtonActive: {
    backgroundColor: '#4A306D',
  },
  scheduleScreenDayButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A306D',
  },
  scheduleScreenDayButtonTextActive: {
    color: '#FFFFFF',
  },
  scheduleScreenDayHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 20,
  },
  scheduleScreenScheduleList: {
    flex: 1,
  },
  scheduleScreenLessonCard: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: '#4A306D',
  },
  scheduleScreenLessonHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  scheduleScreenLessonTime: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
  },
  scheduleScreenWeekBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  scheduleScreenNumeratorBadge: {
    backgroundColor: '#E1F5FE',
  },
  scheduleScreenDenominatorBadge: {
    backgroundColor: '#F3E5F5',
  },
  scheduleScreenWeekBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#4A306D',
  },
  scheduleScreenLessonSubject: {
    fontSize: 16,
    color: '#1F2937',
    marginBottom: 4,
    fontWeight: '600',
  },
  scheduleScreenLessonGroup: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  scheduleScreenLessonClassroom: {
    fontSize: 12,
    color: '#9CA3AF',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  scheduleScreenLessonType: {
    fontSize: 14,
    color: '#5C80BC',
    fontStyle: 'italic',
    marginBottom: 4,
  },
  scheduleScreenAttendanceHint: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  scheduleScreenAttendanceHintText: {
    fontSize: 12,
    color: '#8B3A62',
    fontStyle: 'italic',
  },
  scheduleScreenEmptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  scheduleScreenEmptyStateText: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 8,
  },
  scheduleScreenEmptyStateSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    fontStyle: 'italic',
  },

  // Стили для StudentManagementScreen
  studentManagementScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
  },
  studentManagementScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  studentManagementScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  studentManagementScreenBackButton: {
    marginRight: 15,
  },
  studentManagementScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  studentManagementScreenHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  studentManagementScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  studentManagementScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  studentManagementScreenScrollView: {
    flex: 1,
    padding: 20,
  },
  studentManagementScreenFiltersSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  studentManagementScreenSearchInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#F9FAFB',
    color: '#374151',
    marginBottom: 15,
  },
  studentManagementScreenFilterTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
    marginBottom: 10,
  },
  studentManagementScreenGroupsScroll: {
    marginHorizontal: -5,
  },
  studentManagementScreenGroupsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 5,
  },
  studentManagementScreenGroupFilter: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: '#F3F4F6',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  studentManagementScreenGroupFilterActive: {
    backgroundColor: '#4A306D',
    borderColor: '#4A306D',
  },
  studentManagementScreenGroupFilterText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A306D',
  },
  studentManagementScreenGroupFilterTextActive: {
    color: '#FFFFFF',
  },
  studentManagementScreenAddButton: {
    backgroundColor: '#4A306D',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  studentManagementScreenAddButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  studentManagementScreenStudentsSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  studentManagementScreenSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  studentManagementScreenSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A306D',
  },
  studentManagementScreenStudentsCount: {
    fontSize: 14,
    color: '#6B7280',
  },
  studentManagementScreenLoadingText: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 16,
    padding: 20,
  },
  studentManagementScreenStudentCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: '#F8F7FF',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#4A306D',
  },
  studentManagementScreenStudentInfo: {
    flex: 1,
  },
  studentManagementScreenStudentName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 4,
  },
  studentManagementScreenStudentDetails: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  studentManagementScreenStudentContact: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 2,
  },
  studentManagementScreenStudentActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  studentManagementScreenEditButton: {
    padding: 8,
    marginRight: 8,
  },
  studentManagementScreenEditButtonText: {
    fontSize: 18,
  },
  studentManagementScreenDeleteButton: {
    padding: 8,
  },
  studentManagementScreenDeleteButtonText: {
    fontSize: 18,
  },
  studentManagementScreenEmptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  studentManagementScreenEmptyStateText: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 8,
    textAlign: 'center',
  },
  studentManagementScreenEmptyStateSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },

  // Стили для SubjectDetailScreen
  subjectDetailScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
  },
  subjectDetailScreenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  subjectDetailScreenHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  subjectDetailScreenBackButton: {
    marginRight: 15,
  },
  subjectDetailScreenBackButtonText: {
    fontSize: 24,
    color: '#4A306D',
    fontWeight: 'bold',
  },
  subjectDetailScreenHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4A306D',
    flex: 1,
  },
  subjectDetailScreenLogoutButton: {
    backgroundColor: 'rgba(139, 58, 98, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B3A62',
  },
  subjectDetailScreenLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  subjectDetailScreenScrollView: {
    flex: 1,
    padding: 20,
  },
  subjectDetailScreenLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subjectDetailScreenLoadingText: {
    fontSize: 16,
    color: '#6B7280',
  },
  subjectDetailScreenSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  subjectDetailScreenSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  subjectDetailScreenSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A306D',
  },
  subjectDetailScreenRefreshButton: {
    backgroundColor: 'rgba(92, 128, 188, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  subjectDetailScreenRefreshButtonText: {
    color: '#5C80BC',
    fontSize: 16,
    fontWeight: 'bold',
  },
  subjectDetailScreenGroupsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 15,
  },
  subjectDetailScreenGroupChip: {
    backgroundColor: '#4A306D',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  subjectDetailScreenGroupChipText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  subjectDetailScreenAddButton: {
    backgroundColor: '#F3F4F6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  subjectDetailScreenAddButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
  },
  subjectDetailScreenExportButton: {
    backgroundColor: '#4A306D',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  subjectDetailScreenExportButtonDisabled: {
    backgroundColor: '#9CA3AF',
  },
  subjectDetailScreenExportButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
  },
  subjectDetailScreenScheduleContainer: {
    marginTop: 10,
  },
  subjectDetailScreenDaySection: {
    marginBottom: 20,
  },
  subjectDetailScreenDayTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  subjectDetailScreenLessonItem: {
    backgroundColor: '#F8F7FF',
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#4A306D',
  },
  subjectDetailScreenLessonTime: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  subjectDetailScreenTimeText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A306D',
  },
  subjectDetailScreenWeekBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  subjectDetailScreenNumeratorBadge: {
    backgroundColor: '#E1F5FE',
  },
  subjectDetailScreenDenominatorBadge: {
    backgroundColor: '#F3E5F5',
  },
  subjectDetailScreenBothBadge: {
    backgroundColor: '#E8F5E8',
  },
  subjectDetailScreenWeekBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#4A306D',
  },
  subjectDetailScreenLessonDetails: {
    marginTop: 4,
  },
  subjectDetailScreenGroupText: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 2,
  },
  subjectDetailScreenClassroomText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontStyle: 'italic',
  },
  subjectDetailScreenStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  subjectDetailScreenStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  subjectDetailScreenStatNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 4,
  },
  subjectDetailScreenStatLabel: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
  },
  subjectDetailScreenEmptyState: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  subjectDetailScreenEmptyStateText: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 8,
    textAlign: 'center',
  },
  subjectDetailScreenEmptyStateSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  // Общие стили для компонентов
commonHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  width: '100%',
  paddingHorizontal: 20,
  paddingTop: 60,
  paddingBottom: 16,
  backgroundColor: '#FFFFFF',
  borderBottomWidth: 1,
  borderBottomColor: '#E5E7EB',
  position: 'relative',
  zIndex: 100,
},
commonHeaderLeft: {
  flexDirection: 'row',
  alignItems: 'center',
  flex: 1,
  minWidth: 0, // Важно для правильного обрезания текста
},
commonBackButton: {
  marginRight: 12,
  minWidth: 24, // Фиксированная ширина для выравнивания
  alignItems: 'center',
},
commonBackButtonText: {
  fontSize: 28, // Увеличиваем для лучшего вида
  color: '#4A306D',
  fontWeight: 'bold',
  lineHeight: 32,
},
commonHeaderTitle: {
  fontSize: 24, // Уменьшаем для лучшего вписывания
  fontWeight: 'bold',
  color: '#4A306D',
  flex: 1,
  textAlign: 'left', // Выравниваем по левому краю
  marginRight: 10, // Отступ от кнопки выхода
},
commonLogoutButton: {
  backgroundColor: 'rgba(139, 58, 98, 0.1)',
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: '#8B3A62',
  minWidth: 70, // Фиксированная минимальная ширина
  alignItems: 'center',
},
  commonLogoutButtonText: {
    color: '#8B3A62',
    fontSize: 14,
    fontWeight: '600',
  },
  
  commonSaveButton: {
    backgroundColor: '#4A306D',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  commonSaveButtonDisabled: {
    backgroundColor: '#9CA3AF',
  },
  commonSaveButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  
  commonSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#4A306D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  commonSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A306D',
    marginBottom: 15,
  },
  
  commonInput: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#F9FAFB',
    color: '#374151',
    marginBottom: 16,
  },
  
  commonLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A306D',
    marginBottom: 8,
  },
  requiredStar: {
    color: '#EF4444',
  },
  
  // Общие контейнеры
  commonContainer: {
    flex: 1,
    backgroundColor: '#F8F7FF',
  },
  commonScrollView: {
    flex: 1,
    padding: 20,
  },
  
  // Общие состояния
  commonLoadingText: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 16,
    padding: 20,
  },
  commonEmptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  commonEmptyStateText: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 8,
    textAlign: 'center',
  },
  commonEmptyStateSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  // Добавляем в существующий ScreenStyles.js:

// Общие стили для фильтров
commonFilterChip: {
  paddingHorizontal: 16,
  paddingVertical: 10,
  borderRadius: 20,
  marginRight: 8,
  backgroundColor: '#F3F4F6',
  borderWidth: 2,
  borderColor: '#E5E7EB',
},
commonFilterChipActive: {
  backgroundColor: '#4A306D',
  borderColor: '#4A306D',
},
commonFilterChipText: {
  fontSize: 14,
  fontWeight: '600',
  color: '#4A306D',
},
commonFilterChipTextActive: {
  color: '#FFFFFF',
},

// Общие стили для карточки студента
commonStudentCard: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  backgroundColor: '#F8F7FF',
  padding: 16,
  borderRadius: 12,
  marginBottom: 12,
  borderLeftWidth: 4,
  borderLeftColor: '#4A306D',
},
commonStudentInfo: {
  flex: 1,
},
commonStudentName: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#4A306D',
  marginBottom: 4,
},
commonStudentDetails: {
  fontSize: 14,
  color: '#6B7280',
  marginBottom: 4,
},
commonStudentContact: {
  fontSize: 12,
  color: '#9CA3AF',
  marginBottom: 2,
},
commonStudentActions: {
  flexDirection: 'row',
  alignItems: 'center',
},
commonEditButton: {
  padding: 8,
  marginRight: 8,
},
commonEditButtonText: {
  fontSize: 18,
},
commonDeleteButton: {
  padding: 8,
},
commonDeleteButtonText: {
  fontSize: 18,
},
addStudentScreenHeadmanSwitch: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginTop: 16,
  padding: 12,
  backgroundColor: '#F8F7FF',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
},
});